
services:
  manipulation:
    build: 
      context: ../
      dockerfile: docker/Dockerfile
    container_name: speedpilot
    image: speedpilot:latest

    ipc: host
    network_mode: host
    privileged: true
    devices:
      - /dev/gpiochip0
      - /dev/gpiochip1
      - /dev/gpiochip2
      - /dev/gpiochip3
      - /dev/gpiochip4
    volumes:
      - ../ros2_ws:/root/ros2_ws
    restart: unless-stopped

