
services:
  speedpilot: &speedpilot
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: speedpilot
    image: speedpilot:latest

    ipc: host
    network_mode: host
    privileged: true
    
    ports:
      - 9091:9091
    devices:
      - /dev/gpiochip0
      - /dev/gpiochip1
      - /dev/gpiochip2
      - /dev/gpiochip3
      - /dev/gpiochip4
      - /dev/ttyUSB0
    volumes:
      - ../ros2_ws/src:/root/ros2_ws/src
    restart: unless-stopped
    command: >
      bash -c "
        source /opt/ros/jazzy/setup.bash &&
        source /root/ros2_ws/install/setup.bash &&
        python3 src/car_system_launch.py &
        ros2 launch speedpilot_backend bringup.launch.py &
      "
